import type { Product } from '@/lib/types';

export const mockProducts: Product[] = [
  {
    _id: '1',
    id: '1',
    name: 'Cimento Votorantim Todas as Obras 50kg',
    description: 'Cimento de alta qualidade para todas as etapas da sua obra.',
    category: 'Cimento',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Cimento',
    unit: 'saco',
    unitPrice: 28.90,
    price: 28.90,
    supplier: { _id: '1', name: 'Votorantim Cimentos' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    id: '2',
    name: 'Vergalhão de Aço CA-50 10mm (3/8")',
    description: 'Vergalhão nervurado para estruturas de concreto armado.',
    category: 'Aço',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Vergalhão',
    unit: 'barra',
    unitPrice: 45.50,
    price: 45.50,
    supplier: { _id: '2', name: 'Gerdau' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    id: '3',
    name: 'Tijolo Baiano 9 Furos 14x19x29cm',
    description: 'Tijolo cerâmico de vedação para alvenaria.',
    category: 'Tijolos',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Tijolo',
    unit: 'milheiro',
    unitPrice: 850.00,
    price: 850.00,
    supplier: { _id: '3', name: 'Cerâmica Tatuí' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    id: '4',
    name: 'Areia Média Lavada',
    description: 'Areia utilizada para fabricação de concreto e argamassa.',
    category: 'Agregados',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Areia',
    unit: 'm³',
    unitPrice: 120.00,
    price: 120.00,
    supplier: { _id: '4', name: 'Porto de Areia' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '5',
    id: '5',
    name: 'Tinta Acrílica Fosca Branca Suvinil 18L',
    description: 'Tinta de alta cobertura e rendimento para paredes internas e externas.',
    category: 'Tintas',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Tinta',
    unit: 'lata',
    unitPrice: 350.00,
    price: 350.00,
    supplier: { _id: '5', name: 'Suvinil' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '6',
    id: '6',
    name: 'Telha de Cerâmica Portuguesa',
    description: 'Telha de alta durabilidade e resistência para telhados.',
    category: 'Telhas',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Telha',
    unit: 'unidade',
    unitPrice: 2.50,
    price: 2.50,
    supplier: { _id: '6', name: 'Tégula' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '7',
    id: '7',
    name: 'Caixa d\'Água de Polietileno 1000L',
    description: 'Reservatório de água potável para residências e comércios.',
    category: 'Hidráulica',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Caixa+d\'Água',
    unit: 'unidade',
    unitPrice: 450.00,
    price: 450.00,
    supplier: { _id: '7', name: 'Fortlev' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '8',
    id: '8',
    name: 'Fio Elétrico Flexível 2,5mm²',
    description: 'Cabo flexível para instalações elétricas residenciais.',
    category: 'Elétrica',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Fio+Elétrico',
    unit: 'rolo 100m',
    unitPrice: 180.00,
    price: 180.00,
    supplier: { _id: '8', name: 'Prysmian' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '9',
    id: '9',
    name: 'Argamassa Colante ACIII Quartzolit',
    description: 'Argamassa de alta performance para assentamento de porcelanatos.',
    category: 'Argamassa',
    imageUrl: 'https://placehold.co/400x400/c7d2fe/111827?text=Argamassa',
    unit: 'saco 20kg',
    unitPrice: 35.00,
    price: 35.00,
    supplier: { _id: '9', name: 'Quartzolit' },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
